spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
kafka:
  bootstrap-servers: localhost:9092
  group: myGroup
  topic: top
mq:
  type: "rabbitmq"
rabbit:
  host: localhost
  queue: queue1